services:
  happ-crypto-redirect:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: happ-crypto-redirect-app
    env_file:
      - .env
    ports:
      - "${HOST_PORT:-5500}:3000"
    restart: unless-stopped
